// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mskkbbepotzhsylnagul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1za2tiYmVwb3R6aHN5bG5hZ3VsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczOTU0NDAsImV4cCI6MjA3Mjk3MTQ0MH0.lZ60I19jcxVbLRA0GTeE6Obm3iRWBOLiM_vin3PHZBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});